### ISSUE TITLE
Should this repo be included in Palm?

### ISSUE THREAD

**Issue by mtyaka** [openedx/enterprise-subsidy#47]
The Build-Test-Release Working Group is preparing to cut branches for Palm, the next Open edX release. The cut will happen on April 11th.

The [openedx.yml](https://github.com/openedx/enterprise-subsidy/blob/7d006a04be9939f5f96ff5eb63e0487c50d10c63/openedx.yaml#L20) currently says that this repo should "maybe" be included in the next release.

Is the repo ready to be included in Palm? Or should we wait until Quince, scheduled to be released in December?

@iloveagent57

**Comment by nedbat** [comment]
@iloveagent57 Can you update the openedx.yaml file to indicate this?
